version: "3"
services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: Skele3179
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./postgres.conf:/etc/postgresql/postgresql.conf
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database-data: