version: "3"
services:
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: Skele3179
    volumes:
      - database-data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
